# Generated by Django 3.0.3 on 2020-02-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20200222_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionModel',
            new_name='Session',
        ),
    ]
